services:
  - type: web
    name: ai-secretary-v01
    env: python
    plan: free
    buildCommand: pip install -r requirements-web.txt
    startCommand: gunicorn app:app
    envVars:
      - key: AI_SECRETARY_SECRET_KEY
        generateValue: true
      - key: AI_SECRETARY_LICENSE_KEY
        sync: false
